//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace IDS.EBSTCRM.Base.NNO {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NavneNumreBasisBinding", Namespace="http://tunnel.nno.dk/NNService/1.0")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Subscriber))]
    public partial class NavneNumreBasis : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback lookupSubscribersOperationCompleted;
        
        private System.Threading.SendOrPostCallback lookupSubscribersByIDOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NavneNumreBasis() {
            this.Url = global::IDS.EBSTCRM.Base.Properties.Settings.Default.IDS_EBSTCRM_Base_NNO_NavneNumreBasis;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event lookupSubscribersCompletedEventHandler lookupSubscribersCompleted;
        
        /// <remarks/>
        public event lookupSubscribersByIDCompletedEventHandler lookupSubscribersByIDCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://tunnel.nno.dk/NNService/1.0", ResponseNamespace="http://tunnel.nno.dk/NNService/1.0")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public SubscriberResult lookupSubscribers(SearchQuestion Question_1) {
            object[] results = this.Invoke("lookupSubscribers", new object[] {
                        Question_1});
            return ((SubscriberResult)(results[0]));
        }
        
        /// <remarks/>
        public void lookupSubscribersAsync(SearchQuestion Question_1) {
            this.lookupSubscribersAsync(Question_1, null);
        }
        
        /// <remarks/>
        public void lookupSubscribersAsync(SearchQuestion Question_1, object userState) {
            if ((this.lookupSubscribersOperationCompleted == null)) {
                this.lookupSubscribersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlookupSubscribersOperationCompleted);
            }
            this.InvokeAsync("lookupSubscribers", new object[] {
                        Question_1}, this.lookupSubscribersOperationCompleted, userState);
        }
        
        private void OnlookupSubscribersOperationCompleted(object arg) {
            if ((this.lookupSubscribersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.lookupSubscribersCompleted(this, new lookupSubscribersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://tunnel.nno.dk/NNService/1.0", ResponseNamespace="http://tunnel.nno.dk/NNService/1.0")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public SubscriberResult lookupSubscribersByID(SearchIDQuestion Question_1) {
            object[] results = this.Invoke("lookupSubscribersByID", new object[] {
                        Question_1});
            return ((SubscriberResult)(results[0]));
        }
        
        /// <remarks/>
        public void lookupSubscribersByIDAsync(SearchIDQuestion Question_1) {
            this.lookupSubscribersByIDAsync(Question_1, null);
        }
        
        /// <remarks/>
        public void lookupSubscribersByIDAsync(SearchIDQuestion Question_1, object userState) {
            if ((this.lookupSubscribersByIDOperationCompleted == null)) {
                this.lookupSubscribersByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlookupSubscribersByIDOperationCompleted);
            }
            this.InvokeAsync("lookupSubscribersByID", new object[] {
                        Question_1}, this.lookupSubscribersByIDOperationCompleted, userState);
        }
        
        private void OnlookupSubscribersByIDOperationCompleted(object arg) {
            if ((this.lookupSubscribersByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.lookupSubscribersByIDCompleted(this, new lookupSubscribersByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://tunnel.nno.dk/NNService/1.0/Types")]
    public partial class SearchQuestion {
        
        private string phoneField;
        
        private string phonetypeField;
        
        private string nameField;
        
        private string startswithField;
        
        private string phoneticsField;
        
        private string streetField;
        
        private string streetstartswithField;
        
        private string housenumberField;
        
        private string zipField;
        
        private string districtField;
        
        private string municipalitycodeField;
        
        private string isbusinessField;
        
        private string sortorderField;
        
        private string usernameField;
        
        /// <remarks/>
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string phonetype {
            get {
                return this.phonetypeField;
            }
            set {
                this.phonetypeField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string startswith {
            get {
                return this.startswithField;
            }
            set {
                this.startswithField = value;
            }
        }
        
        /// <remarks/>
        public string phonetics {
            get {
                return this.phoneticsField;
            }
            set {
                this.phoneticsField = value;
            }
        }
        
        /// <remarks/>
        public string street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        public string streetstartswith {
            get {
                return this.streetstartswithField;
            }
            set {
                this.streetstartswithField = value;
            }
        }
        
        /// <remarks/>
        public string housenumber {
            get {
                return this.housenumberField;
            }
            set {
                this.housenumberField = value;
            }
        }
        
        /// <remarks/>
        public string zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        public string district {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
            }
        }
        
        /// <remarks/>
        public string municipalitycode {
            get {
                return this.municipalitycodeField;
            }
            set {
                this.municipalitycodeField = value;
            }
        }
        
        /// <remarks/>
        public string isbusiness {
            get {
                return this.isbusinessField;
            }
            set {
                this.isbusinessField = value;
            }
        }
        
        /// <remarks/>
        public string sortorder {
            get {
                return this.sortorderField;
            }
            set {
                this.sortorderField = value;
            }
        }
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://tunnel.nno.dk/NNService/1.0/Types")]
    public partial class SearchIDQuestion {
        
        private long tDC_PIDField;
        
        private string usernameField;
        
        /// <remarks/>
        public long TDC_PID {
            get {
                return this.tDC_PIDField;
            }
            set {
                this.tDC_PIDField = value;
            }
        }
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://tunnel.nno.dk/NNService/1.0/Types")]
    public partial class Subscriber {
        
        private long tDC_PIDField;
        
        private string titleField;
        
        private string christiannameField;
        
        private string surnameField;
        
        private string companynameField;
        
        private string zipcodeField;
        
        private string districtField;
        
        private string addressField;
        
        private string streetnameField;
        
        private string housenumberfromField;
        
        private string housenumbertoField;
        
        private string houseletterfromField;
        
        private string houselettertoField;
        
        private string floorField;
        
        private string directionField;
        
        private string doorField;
        
        private string villageField;
        
        private string phoneField;
        
        private int phonetypeField;
        
        private int ismainField;
        
        private int isfaxField;
        
        private int isbusinessField;
        
        private string emailField;
        
        private string wwwField;
        
        private string municipalitycodeField;
        
        private string streetcodeField;
        
        private int displayinfoField;
        
        /// <remarks/>
        public long TDC_PID {
            get {
                return this.tDC_PIDField;
            }
            set {
                this.tDC_PIDField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string christianname {
            get {
                return this.christiannameField;
            }
            set {
                this.christiannameField = value;
            }
        }
        
        /// <remarks/>
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        public string companyname {
            get {
                return this.companynameField;
            }
            set {
                this.companynameField = value;
            }
        }
        
        /// <remarks/>
        public string zipcode {
            get {
                return this.zipcodeField;
            }
            set {
                this.zipcodeField = value;
            }
        }
        
        /// <remarks/>
        public string district {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
            }
        }
        
        /// <remarks/>
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string streetname {
            get {
                return this.streetnameField;
            }
            set {
                this.streetnameField = value;
            }
        }
        
        /// <remarks/>
        public string housenumberfrom {
            get {
                return this.housenumberfromField;
            }
            set {
                this.housenumberfromField = value;
            }
        }
        
        /// <remarks/>
        public string housenumberto {
            get {
                return this.housenumbertoField;
            }
            set {
                this.housenumbertoField = value;
            }
        }
        
        /// <remarks/>
        public string houseletterfrom {
            get {
                return this.houseletterfromField;
            }
            set {
                this.houseletterfromField = value;
            }
        }
        
        /// <remarks/>
        public string houseletterto {
            get {
                return this.houselettertoField;
            }
            set {
                this.houselettertoField = value;
            }
        }
        
        /// <remarks/>
        public string floor {
            get {
                return this.floorField;
            }
            set {
                this.floorField = value;
            }
        }
        
        /// <remarks/>
        public string direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        public string door {
            get {
                return this.doorField;
            }
            set {
                this.doorField = value;
            }
        }
        
        /// <remarks/>
        public string village {
            get {
                return this.villageField;
            }
            set {
                this.villageField = value;
            }
        }
        
        /// <remarks/>
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public int phonetype {
            get {
                return this.phonetypeField;
            }
            set {
                this.phonetypeField = value;
            }
        }
        
        /// <remarks/>
        public int ismain {
            get {
                return this.ismainField;
            }
            set {
                this.ismainField = value;
            }
        }
        
        /// <remarks/>
        public int isfax {
            get {
                return this.isfaxField;
            }
            set {
                this.isfaxField = value;
            }
        }
        
        /// <remarks/>
        public int isbusiness {
            get {
                return this.isbusinessField;
            }
            set {
                this.isbusinessField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string www {
            get {
                return this.wwwField;
            }
            set {
                this.wwwField = value;
            }
        }
        
        /// <remarks/>
        public string municipalitycode {
            get {
                return this.municipalitycodeField;
            }
            set {
                this.municipalitycodeField = value;
            }
        }
        
        /// <remarks/>
        public string streetcode {
            get {
                return this.streetcodeField;
            }
            set {
                this.streetcodeField = value;
            }
        }
        
        /// <remarks/>
        public int displayinfo {
            get {
                return this.displayinfoField;
            }
            set {
                this.displayinfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://tunnel.nno.dk/NNService/1.0/Types")]
    public partial class SubscriberResult {
        
        private string errorMessageField;
        
        private int subscribersfoundField;
        
        private Subscriber[] subscribersField;
        
        /// <remarks/>
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public int subscribersfound {
            get {
                return this.subscribersfoundField;
            }
            set {
                this.subscribersfoundField = value;
            }
        }
        
        /// <remarks/>
        public Subscriber[] subscribers {
            get {
                return this.subscribersField;
            }
            set {
                this.subscribersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void lookupSubscribersCompletedEventHandler(object sender, lookupSubscribersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class lookupSubscribersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal lookupSubscribersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SubscriberResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SubscriberResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void lookupSubscribersByIDCompletedEventHandler(object sender, lookupSubscribersByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class lookupSubscribersByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal lookupSubscribersByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SubscriberResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SubscriberResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591